/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_FEE"
      | "MAX_PLAYERS"
      | "enterLottery"
      | "getLotteryInfo"
      | "getPlayerCount"
      | "getPlayers"
      | "hasEntered"
      | "hasPlayerEntered"
      | "lastWinner"
      | "lotteryRound"
      | "players"
      | "totalPrizePool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LotteryReset" | "PlayerEntered" | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ENTRY_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_PLAYERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enterLottery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLotteryInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasEntered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPlayerEntered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastWinner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPrizePool",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ENTRY_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLAYERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotteryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasEntered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasPlayerEntered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lotteryRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPrizePool",
    data: BytesLike
  ): Result;
}

export namespace LotteryResetEvent {
  export type InputTuple = [newRound: BigNumberish];
  export type OutputTuple = [newRound: bigint];
  export interface OutputObject {
    newRound: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerEnteredEvent {
  export type InputTuple = [
    player: AddressLike,
    round: BigNumberish,
    playerCount: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    round: bigint,
    playerCount: bigint
  ];
  export interface OutputObject {
    player: string;
    round: bigint;
    playerCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    winner: AddressLike,
    round: BigNumberish,
    prizeAmount: BigNumberish
  ];
  export type OutputTuple = [
    winner: string,
    round: bigint,
    prizeAmount: bigint
  ];
  export interface OutputObject {
    winner: string;
    round: bigint;
    prizeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Lottery extends BaseContract {
  connect(runner?: ContractRunner | null): Lottery;
  waitForDeployment(): Promise<this>;

  interface: LotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_PLAYERS: TypedContractMethod<[], [bigint], "view">;

  enterLottery: TypedContractMethod<[], [void], "payable">;

  getLotteryInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string, boolean] & {
        currentRound: bigint;
        playerCount: bigint;
        prizePool: bigint;
        winner: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getPlayerCount: TypedContractMethod<[], [bigint], "view">;

  getPlayers: TypedContractMethod<[], [string[]], "view">;

  hasEntered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasPlayerEntered: TypedContractMethod<
    [player: AddressLike],
    [boolean],
    "view"
  >;

  lastWinner: TypedContractMethod<[], [string], "view">;

  lotteryRound: TypedContractMethod<[], [bigint], "view">;

  players: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalPrizePool: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PLAYERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enterLottery"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getLotteryInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string, boolean] & {
        currentRound: bigint;
        playerCount: bigint;
        prizePool: bigint;
        winner: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasEntered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasPlayerEntered"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastWinner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lotteryRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalPrizePool"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LotteryReset"
  ): TypedContractEvent<
    LotteryResetEvent.InputTuple,
    LotteryResetEvent.OutputTuple,
    LotteryResetEvent.OutputObject
  >;
  getEvent(
    key: "PlayerEntered"
  ): TypedContractEvent<
    PlayerEnteredEvent.InputTuple,
    PlayerEnteredEvent.OutputTuple,
    PlayerEnteredEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "LotteryReset(uint256)": TypedContractEvent<
      LotteryResetEvent.InputTuple,
      LotteryResetEvent.OutputTuple,
      LotteryResetEvent.OutputObject
    >;
    LotteryReset: TypedContractEvent<
      LotteryResetEvent.InputTuple,
      LotteryResetEvent.OutputTuple,
      LotteryResetEvent.OutputObject
    >;

    "PlayerEntered(address,uint256,uint256)": TypedContractEvent<
      PlayerEnteredEvent.InputTuple,
      PlayerEnteredEvent.OutputTuple,
      PlayerEnteredEvent.OutputObject
    >;
    PlayerEntered: TypedContractEvent<
      PlayerEnteredEvent.InputTuple,
      PlayerEnteredEvent.OutputTuple,
      PlayerEnteredEvent.OutputObject
    >;

    "WinnerSelected(address,uint256,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
