/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Employee } from "./Employee";
export type { IEmployee } from "./IEmployee";
export * as factories from "./factories";
export { Employee__factory } from "./factories/Employee__factory";
export { IEmployee__factory } from "./factories/IEmployee__factory";
