/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AccessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOrUpdateEmployee"
      | "canAccessGarage"
      | "employeeAddresses"
      | "employees"
      | "getAllEmployees"
      | "getEmployeeDetails"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addOrUpdateEmployee",
    values: [AddressLike, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "canAccessGarage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employeeAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeDetails",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOrUpdateEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAccessGarage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employeeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeDetails",
    data: BytesLike
  ): Result;
}

export interface Access extends BaseContract {
  connect(runner?: ContractRunner | null): Access;
  waitForDeployment(): Promise<this>;

  interface: AccessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOrUpdateEmployee: TypedContractMethod<
    [
      _wallet: AddressLike,
      _name: string,
      _role: BigNumberish,
      _isEmployed: boolean
    ],
    [void],
    "nonpayable"
  >;

  canAccessGarage: TypedContractMethod<
    [_wallet: AddressLike],
    [boolean],
    "view"
  >;

  employeeAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  employees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean] & {
        name: string;
        role: bigint;
        isEmployed: boolean;
      }
    ],
    "view"
  >;

  getAllEmployees: TypedContractMethod<[], [string[]], "view">;

  getEmployeeDetails: TypedContractMethod<
    [_wallet: AddressLike],
    [
      [string, bigint, boolean] & {
        name: string;
        role: bigint;
        isEmployed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOrUpdateEmployee"
  ): TypedContractMethod<
    [
      _wallet: AddressLike,
      _name: string,
      _role: BigNumberish,
      _isEmployed: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canAccessGarage"
  ): TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "employeeAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean] & {
        name: string;
        role: bigint;
        isEmployed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEmployees"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEmployeeDetails"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [
      [string, bigint, boolean] & {
        name: string;
        role: bigint;
        isEmployed: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
