/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Access } from "./Access";
export * as factories from "./factories";
export { Access__factory } from "./factories/Access__factory";
