/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EmployeeFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "allManagers" | "createManager" | "getAllManagers"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ManagerCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allManagers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllManagers",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllManagers",
    data: BytesLike
  ): Result;
}

export namespace ManagerCreatedEvent {
  export type InputTuple = [managerAddress: AddressLike, owner: AddressLike];
  export type OutputTuple = [managerAddress: string, owner: string];
  export interface OutputObject {
    managerAddress: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EmployeeFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EmployeeFactory;
  waitForDeployment(): Promise<this>;

  interface: EmployeeFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allManagers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createManager: TypedContractMethod<[], [string], "nonpayable">;

  getAllManagers: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allManagers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createManager"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllManagers"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "ManagerCreated"
  ): TypedContractEvent<
    ManagerCreatedEvent.InputTuple,
    ManagerCreatedEvent.OutputTuple,
    ManagerCreatedEvent.OutputObject
  >;

  filters: {
    "ManagerCreated(address,address)": TypedContractEvent<
      ManagerCreatedEvent.InputTuple,
      ManagerCreatedEvent.OutputTuple,
      ManagerCreatedEvent.OutputObject
    >;
    ManagerCreated: TypedContractEvent<
      ManagerCreatedEvent.InputTuple,
      ManagerCreatedEvent.OutputTuple,
      ManagerCreatedEvent.OutputObject
    >;
  };
}
