/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchoolMS } from "./SchoolMS";
export * as factories from "./factories";
export { SchoolMS__factory } from "./factories/SchoolMS__factory";
