/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iuniswappairSol from "./IUNISWAPPAIR.sol";
export type { iuniswappairSol };
import type * as iUniswapV2Router01Sol from "./IUniswapV2Router01.sol";
export type { iUniswapV2Router01Sol };
export type { IERC20 } from "./IERC20";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
