/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Employee__factory } from "./Employee__factory";
export { IEmployee__factory } from "./IEmployee__factory";
