/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as employeefactorySol from "./Employeefactory.sol";
export type { employeefactorySol };
export type { Employee } from "./Employee";
export type { IEmployee } from "./IEmployee";
export * as factories from "./factories";
export { Employee__factory } from "./factories/Employee__factory";
export type { EmployeeFactory } from "./Employeefactory.sol/EmployeeFactory";
export { EmployeeFactory__factory } from "./factories/Employeefactory.sol/EmployeeFactory__factory";
export { IEmployee__factory } from "./factories/IEmployee__factory";
